default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: todo_list_dev

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
